// Generated by gencpp from file baraja/SetPlaytableRequest.msg
// DO NOT EDIT!


#ifndef BARAJA_MESSAGE_SETPLAYTABLEREQUEST_H
#define BARAJA_MESSAGE_SETPLAYTABLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baraja
{
template <class ContainerAllocator>
struct SetPlaytableRequest_
{
  typedef SetPlaytableRequest_<ContainerAllocator> Type;

  SetPlaytableRequest_()
    : playtable()  {
    }
  SetPlaytableRequest_(const ContainerAllocator& _alloc)
    : playtable(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _playtable_type;
  _playtable_type playtable;





  typedef boost::shared_ptr< ::baraja::SetPlaytableRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baraja::SetPlaytableRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetPlaytableRequest_

typedef ::baraja::SetPlaytableRequest_<std::allocator<void> > SetPlaytableRequest;

typedef boost::shared_ptr< ::baraja::SetPlaytableRequest > SetPlaytableRequestPtr;
typedef boost::shared_ptr< ::baraja::SetPlaytableRequest const> SetPlaytableRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baraja::SetPlaytableRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baraja::SetPlaytableRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::baraja::SetPlaytableRequest_<ContainerAllocator1> & lhs, const ::baraja::SetPlaytableRequest_<ContainerAllocator2> & rhs)
{
  return lhs.playtable == rhs.playtable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::baraja::SetPlaytableRequest_<ContainerAllocator1> & lhs, const ::baraja::SetPlaytableRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace baraja

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baraja::SetPlaytableRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baraja::SetPlaytableRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baraja::SetPlaytableRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35d5e5d6241fd7567b70565e1f476490";
  }

  static const char* value(const ::baraja::SetPlaytableRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35d5e5d6241fd756ULL;
  static const uint64_t static_value2 = 0x7b70565e1f476490ULL;
};

template<class ContainerAllocator>
struct DataType< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baraja/SetPlaytableRequest";
  }

  static const char* value(const ::baraja::SetPlaytableRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string playtable\n"
;
  }

  static const char* value(const ::baraja::SetPlaytableRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.playtable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPlaytableRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baraja::SetPlaytableRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baraja::SetPlaytableRequest_<ContainerAllocator>& v)
  {
    s << indent << "playtable: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.playtable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BARAJA_MESSAGE_SETPLAYTABLEREQUEST_H
