// Generated by gencpp from file baraja/SetPlaytableResponse.msg
// DO NOT EDIT!


#ifndef BARAJA_MESSAGE_SETPLAYTABLERESPONSE_H
#define BARAJA_MESSAGE_SETPLAYTABLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace baraja
{
template <class ContainerAllocator>
struct SetPlaytableResponse_
{
  typedef SetPlaytableResponse_<ContainerAllocator> Type;

  SetPlaytableResponse_()
    : success(false)  {
    }
  SetPlaytableResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::baraja::SetPlaytableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::baraja::SetPlaytableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetPlaytableResponse_

typedef ::baraja::SetPlaytableResponse_<std::allocator<void> > SetPlaytableResponse;

typedef boost::shared_ptr< ::baraja::SetPlaytableResponse > SetPlaytableResponsePtr;
typedef boost::shared_ptr< ::baraja::SetPlaytableResponse const> SetPlaytableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::baraja::SetPlaytableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::baraja::SetPlaytableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::baraja::SetPlaytableResponse_<ContainerAllocator1> & lhs, const ::baraja::SetPlaytableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::baraja::SetPlaytableResponse_<ContainerAllocator1> & lhs, const ::baraja::SetPlaytableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace baraja

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::baraja::SetPlaytableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::baraja::SetPlaytableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::baraja::SetPlaytableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::baraja::SetPlaytableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baraja/SetPlaytableResponse";
  }

  static const char* value(const ::baraja::SetPlaytableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::baraja::SetPlaytableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPlaytableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::baraja::SetPlaytableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::baraja::SetPlaytableResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BARAJA_MESSAGE_SETPLAYTABLERESPONSE_H
